package dev.funkymuse.fosho.navigator.codegen.argument

enum class ArgumentType {
    INT, STRING, BOOLEAN, FLOAT, LONG,
    BOOLEAN_ARRAY, FLOAT_ARRAY, INT_ARRAY, LONG_ARRAY, STRING_ARRAY,
    BOOLEAN_ARRAY_LIST, FLOAT_ARRAY_LIST, INT_ARRAY_LIST, LONG_ARRAY_LIST, STRING_ARRAY_LIST,
    URI, FILE
}